name: Test Matrix

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['17', '21']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
        
    - name: Set executable permission for mvnw (Unix)
      if: runner.os != 'Windows'
      run: chmod +x ./mvnw
          
    - name: Build and compile
      shell: bash
      run: ./mvnw clean compile
        
    - name: Run tests (skip DB-dependent tests)
      shell: bash
      run: ./mvnw test 